<?php
return [
    [
        "name" => "Suite Susa",
        "description" => "New M4 under the house!!!
        Cozy and bright open space overlooking Piazzale Susa. On the second floor of an ancient building.",
        "lat" => "45.4681",
        "lon" => '9.22382',
        "address" => "Piazzale Susa, Milano",
        "rooms" => "2",
        "beds" => "4",
        "bathrooms" => "1",
        "mq" => "80",
        "cover_image" => "",

    ],
    [
        "name" => "Room with view, in Piazza Giuseppe Pasolini",
        "description" => "Cozy place, with plenty of space and transportation nearby",
        "lat" => "45.49624",
        "lon" => '9.18597',
        "address" => "Piazza Giuseppe Pasolini, Milano",
        "rooms" => "2",
        "beds" => "2",
        "bathrooms" => "1",
        "mq" => "50",
        "cover_image" => "",
    ],
    [
        "name" => "BB BnB near Vatican City",
        "description" => "Lovely bnb, with european breakfast and close to the Vatican City",
        "lat" => "41.90021",
        "lon" => '9.18597',
        "address" => "via dei cavalleggeri, Roma",
        "rooms" => "1",
        "beds" => "2",
        "bathrooms" => "1",
        "mq" => "30",
        "cover_image" => "",
    ],
    [
        "name" => "Cheap rooms close to Termini Station",
        "description" => "Cheap rooms, with plenty of services, open space area for all the guests",
        "lat" => "41.90559",
        "lon" => '12.50202',
        "address" => "via gaeta, Roma",
        "rooms" => "1",
        "beds" => "2",
        "bathrooms" => "2",
        "mq" => "30",
        "cover_image" => "",
    ],
    [
        "name" => "Lovely apartment, in Suffolk street",
        "description" => "Lovely apartment, close to the theater and the national gallery ",
        "lat" => "51.5084",
        "lon" => '-0.13045',
        "address" => "4 suffolk st, London",
        "rooms" => "3",
        "beds" => "4",
        "bathrooms" => "2",
        "mq" => "80",
        "cover_image" => "",
    ],
    [
        "name" => "Open space near St James's Square",
        "description" => "Open space with lovely view of the square closeby and easy access to public transportation",
        "lat" => "51.51181",
        "lon" => '-0.12379',
        "address" => "1 king street, London",
        "rooms" => "4",
        "beds" => "3",
        "bathrooms" => "1",
        "mq" => "100",
        "cover_image" => "",
    ],
    [
        "name" => "Apartment near Savage Gardens",
        "description" => "Small Apartment close to Savage gardens and London Wall, plenty to visit around here!",
        "lat" => "51.5108",
        "lon" => '-0.07758',
        "address" => "10 Pepys St, London",
        "rooms" => "2",
        "beds" => "3",
        "bathrooms" => "1",
        "mq" => "70",
        "cover_image" => "",
    ],
    [
        "name" => "CCRooms, Cozy rooms affordable ",
        "description" => "Cozy rooms close to Termini Station and a library, perfect for students before an exam!, shared bathrooms",
        "lat" => "41.89907",
        "lon" => '12.5154',
        "address" => "Via Tiburtina 139, Roma",
        "rooms" => "1",
        "beds" => "1",
        "bathrooms" => "0",
        "mq" => "30",
        "cover_image" => "",
    ],
    [
        "name" => "Beautiful House Near Lake",
        "description" => "Open space with lovely view of the lake nearby and easy access to public transportation",
        "lat" => '46.14259',
        "lon" => '9.30393',
        "address" => "Via Malacrida, Menaggio",
        "rooms" => "5",
        "beds" => "3",
        "bathrooms" => "2",
        "mq" => "120",
        "cover_image" => "",
    ],
    [
        "name" => "Off-grid dome house on eco mango farm",
        "description" => "This accommodation is unique in the region because of its perfect location and complete facilities. Have you ever slept in a dome house with an evening view of the city skyline and the coastline? The property is a green eco-stay accommodation. Eletricity is generated through solar panels and waste water is reused for irrigation of the trees. We ask you to help us stay as green as possible.",
        "lat" => "36.77864",
        "lon" => '-4.10068',
        "address" => "Vélez-Málaga, Andalusia, Spain",
        "rooms" => "1",
        "beds" => "1",
        "bathrooms" => "1",
        "mq" => "25",
        "cover_image" => "",

    ],
    [
        "name" => "Entire Villa",
        "description" => "Wonderful private villas with panoramic views of the Sierra de Gredos, less than an hour and a half from Madrid. To make your getaway perfect.",
        "lat" => "40.14267",
        "lon" => '-4.98192',
        "address" => "Hontanares, Arenas de San Pedro, Ávila, Spain",
        "rooms" => "2",
        "beds" => "4",
        "bathrooms" => "1",
        "mq" => "45",
        "cover_image" => "",

    ],
    [
        "name" => "Luxury Loft",
        "description" => "A beautiful natural park to walk and the core of the capital's communications. Located in San Sebastian de los Reyes, this loft offers a unique opportunity to enjoy the peace of the suburbs without sacrificing the vibrant life of the city.",
        "lat" => "40.54751",
        "lon" => '-3.62639',
        "address" => "San Sebastián de los Reyes, Comunidad de Madrid, Spain",
        "rooms" => "2",
        "beds" => "3",
        "bathrooms" => "1",
        "mq" => "55",
        "cover_image" => "",

    ],
    [
        "name" => "Modern apartment with terrace",
        "description" => "Natural beaches of the Delta, golf course and 10 min , 20 min (car ) Palma beach and Palma capital",
        "lat" => "39.42049",
        "lon" => '2.78507',
        "address" => "Sa Torre , Llucmajor Baleares, Spain",
        "rooms" => "3",
        "beds" => "6",
        "bathrooms" => "2",
        "mq" => "65",
        "cover_image" => "",

    ],
    [
        "name" => "Traumferien auf Mallorca - Roca Murada",
        "description" => "Wake up in the morning at sea noise and fall asleep in the evening - that sounds like pure holidays! Our apartment was completely renovated in winter 2022/23!",
        "lat" => "39.57434",
        "lon" => '3.20142',
        "address" => "Manacor, Illes Balears, Spain",
        "rooms" => "2",
        "beds" => "2",
        "bathrooms" => "1",
        "mq" => "35",
        "cover_image" => "",

    ],
    [
        "name" => "Chalet Ravna Gora",
        "description" => "Located in the very heart of Croatia largest forested area Gorski Kotar this fully wooden mountain lodge offers cozy rooms, sauna and fireplace spreading the charm of a stylish mountain chalet.
        Surrounded with evergreen forest and mountain peaks,  experience true stress free and energy charging oasis.",
        "lat" => "45.41374",
        "lon" => '14.84913',
        "address" => "Ravna Gora, Croazia",
        "rooms" => "4",
        "beds" => "2",
        "bathrooms" => "2",
        "mq" => "47",
        "cover_image" => "",
    ],
    [
        "name" => "Forest Dream",
        "description" => "The treehouse is a romantic room immersed in the pine trees with fire place for the winter and AC for the summer. It offers a bedroom with a queen size bed, a small kitchenette with stove and fridge; a bathroom with shower, and a private outdoor terrace. And a fantastic view towards the Tuscan landscape!
        And if you want to see and know more about our passion for the interior design, the arts and crafts, and antiques you should come visit our design and make shop, in the Santo Spirito district of Florence!",
        "lat" => "43.72417",
        "lon" => '11.22568',
        "address" => "via Volterrana, Firenze",
        "rooms" => "2",
        "beds" => "3",
        "bathrooms" => "1",
        "mq" => "51",
        "cover_image" => "",
    ],
    [
        "name" => "Room in Latina with view",
        "description" => "Room in Latina, close to the main plaza and the main road, plenty of shops to visit",
        "lat" => "41.46673",
        "lon" => '12.90275',
        "address" => "Via Duca del mare 1, Latina",
        "rooms" => "1",
        "beds" => "1",
        "bathrooms" => "1",
        "mq" => "40",
        "cover_image" => "",
    ],
    [
        "name" => "Luxury chalet sleeps",
        "description" => "Magnificent luxury chalet with sauna, terrace and balcony. Luxury accommodation with a sauna on the piste and just five minutes walk from the cosmopolitan shops and restaurants of La Clusaz, this has to be the perfect choice for a large family group or friends holidaying together. After an energetic day in the mountains, Lodge Le Grizzly is the perfect place to come home to.",
        "lat" => "45.86113",
        "lon" => '6.53096',
        "address" => "La Clusaz, Haute Savoie, Francia",
        "rooms" => "6",
        "beds" => "7",
        "bathrooms" => "4",
        "mq" => "103",
        "cover_image" => "",
    ],
    [
        "name" => "Villa Golfo Aranci",
        "description" => "Baia Caddinas is the renowned residential neighborhood on the outskirts of the pretty Golfo Aranci. Golfo Aranci stands on one of the most beautiful and renowned stretches of coast in all of Sardinia, characterized by white sand beaches, crystal clear sea and the splendid horizon bordered by the unmistakable profile of the island of Tavolara and the imposing promontory of Capo Figari. The town is characterized by the presence of numerous beaches, shops of all kinds, excellent fish restaurants and a lovely tourist port. This prestigious villa is located within the Baia Caddinas residential complex.",
        "lat" => "41.0038",
        "lon" => '9.61676',
        "address" => "Golfo Aranci, Sardegna",
        "rooms" => "6",
        "beds" => "5",
        "bathrooms" => "4",
        "mq" => "82",
        "cover_image" => "",
    ],
    [
        "name" => "Montargil, Portugal Farmhouse",
        "description" => "The Chalet do Lago is made up of 5 bungalows. There are 4 bungalows next to the lake swimming pool and a private area, about 150 meters away from the lake swimming pool. We encourage you to experience some activities that the Alentejo and Barragem de Montargil are waiting for you to offer: Water parks, horse riding, herd exploration, boat passes, bicycle passes, among others.",
        "lat" => "39.07867",
        "lon" => '-8.17058',
        "address" => "Montargil, Portalegre, Portogallo",
        "rooms" => "2",
        "beds" => "2",
        "bathrooms" => "1",
        "mq" => "36",
        "cover_image" => "",
    ],
    [
        "name" => "Nice House In The Snowy Mountains",
        "description" => "fresh air at 5km altitude,enjoy temperatures between 5° and -20°.Really healty,as you will understand the comforts of a heathed house,wich by the 
         way,this is not",
        "lat" => '45.79502',
        "lon" => '6.96588',
        "address" => "Via Dello Stadio,Courmayeur",
        "rooms" => "5",
        "beds" => "3",
        "bathrooms" => "2",
        "mq" => "120",
        "cover_image" => "",
    ],
    [
        "name" => "Beautiful House Near River",
        "description" => "Nice House near the river and the statue of the famous Cyrano!",
        "lat" => '44.85873',
        "lon" => '6.96588',
        "address" => "Rue Honore De Balzac, Bergerac",
        "rooms" => "4",
        "beds" => "2",
        "bathrooms" => "2",
        "mq" => "105",
        "cover_image" => "",
    ],
    [
        "name" => "Traiano guest house",
        "description" => "Traiano guest house is a bed and breakfast located in Benevento, 164 feet from the Arch of Trajan. This bed and breakfast also has free WiFi.",
        "lat" => "41.13232",
        "lon" => '14.7797',
        "address" => "Via Giovanni de Nicastro, Benevento, Italy",
        "rooms" => "2",
        "beds" => "2",
        "bathrooms" => "1",
        "mq" => "35",
        "cover_image" => "",

    ],
    [
        "name" => "Villa Yiara",
        "description" => "Featuring a sea-view terrace in each room, Residence Villa Yiara is an adult-only property housed in an 18th-century building. Overlooking the bay of Positano.",
        "lat" => "40.62929",
        "lon" => '14.48294',
        "address" => "Viale Pasitea, Positano, Italy",
        "rooms" => "3",
        "beds" => "5",
        "bathrooms" => "2",
        "mq" => "25",
        "cover_image" => "",

    ],
    [
        "name" => "Villa 4 Colonne",
        "description" => "Villa 4 Colonne, Capri enjoys a location in Capri, 1.3 miles from Marina Piccola Bay and 1.3 miles from Marina Grande Beach.",
        "lat" => "40.54726",
        "lon" => '14.24944',
        "address" => "Via Tragara, Capri, Italy",
        "rooms" => "2",
        "beds" => "2",
        "bathrooms" => "3",
        "mq" => "250",
        "cover_image" => "",

    ],
    [
        "name" => "Angiolina Apartments",
        "description" => "Set 1804 feet from Piazza Tasso in Sorrento, Angiolina Apartments offers self-catering accommodations with a balcony and free WiFi.",
        "lat" => "40.6241",
        "lon" => '14.37657',
        "address" => "Via degli Aranci, Sorrento, Italy",
        "rooms" => "2",
        "beds" => "2",
        "bathrooms" => "1",
        "mq" => "40",
        "cover_image" => "",

    ],
    [
        "name" => "Casa Flo",
        "description" => "Casa Fló is a sustainable apartment in Salerno, a 10-minute walk from Santa Teresa Beach. This property encourages guests to embrace nature with its eco-friendly arrangements.",
        "lat" => "40.67955",
        "lon" => '14.76054',
        "address" => "Via degli Aranci, Sorrento, Italy",
        "rooms" => "2",
        "beds" => "3",
        "bathrooms" => "1",
        "mq" => "70",
        "cover_image" => "",

    ],
    [
        "name" => "Apartment in the Center",
        "description" => "Appartment in the center of the city",
        "lat" => '50.07543',
        "lon" => '14.45524',
        "address" => "Korunni,Praga",
        "rooms" => "3",
        "beds" => "1",
        "bathrooms" => "1",
        "mq" => "90",
        "cover_image" => "",
    ],
    [
        "name" => "BnB in the Center",
        "description" => "bnb in the center",
        "lat" => '38.99385',
        "lon" => '-1.85645',
        "address" => "Calle Rosario,Albacete",
        "rooms" => "3",
        "beds" => "1",
        "bathrooms" => "2",
        "mq" => "90",
        "cover_image" => "",
    ],




];